// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABgTMwfjk1hXJdD0tDWD3LUrx9jBamFBM',
    appId: '1:593018592282:web:b51d9805967477e933c5a3',
    messagingSenderId: '593018592282',
    projectId: 'chat-app-356c8',
    authDomain: 'chat-app-356c8.firebaseapp.com',
    storageBucket: 'chat-app-356c8.appspot.com',
    measurementId: 'G-PXPSSJ3ZRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8HidkP8m1MPn1xydO0XC7HDnQNqNv_So',
    appId: '1:593018592282:android:94197cfc7c0c4fc833c5a3',
    messagingSenderId: '593018592282',
    projectId: 'chat-app-356c8',
    storageBucket: 'chat-app-356c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH3C35YwYj4HDUiEC_tQYiEWfZ8nv-Dyg',
    appId: '1:593018592282:ios:2b61f689b919c7b733c5a3',
    messagingSenderId: '593018592282',
    projectId: 'chat-app-356c8',
    storageBucket: 'chat-app-356c8.appspot.com',
    iosClientId: '593018592282-5e0fkm1icacr5po3cjd09lljt7ftldlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
